export const SHOP_CREATE_SUCCESS = "SHOP_CREATE_SUCCESS";
export const SHOP_CREATE_FAIL = "SHOP_CREATE_FAIL";

export const SHOP_LOADED_SUCCESS = "SHOP_LOADED_SUCCESS";
export const SHOP_LOADED_FAIL = "SHOP_LOADED_FAIL";
